### ISSUE TITLE
Hover flicker

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/exploding-robot-head#1]
Hi @thomasjbradley :) I got this one working, except when I hover the pieces flicker, and don't register as hovering with Markbot. Any suggestions?? Thanks!

**Comment by thomasjbradley** [comment]
Did you figure out the flickering?

For Markbot, the head pieces need to move upwards as well as out.

**Comment by cmvolden** [comment]
Ohh! That makes sense. The flickering was due to the pieces not moving
together, but I fixed it by putting hover on .robot instead.

Submitted, thank you!!
